FROM python:3.11-slim

WORKDIR /app
COPY . .

RUN ls -la /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libffi-dev build-essential curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt flask supervisor

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 8080
ENV PORT=8080

CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
