# Generated by Django 5.2.2 on 2025-06-11 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='The name of the company being scanned.', max_length=255)),
                ('company_url', models.URLField(blank=True, help_text='The primary URL of the company.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='The current status of the overall scan job.', max_length=20)),
                ('final_report', models.JSONField(blank=True, help_text='The final, synthesized report from the Orchestrator.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(help_text='The name of the worker agent that produced this result.', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], default='SUCCESS', max_length=20)),
                ('raw_output', models.JSONField(help_text='The raw JSON output from the worker agent.')),
                ('error_message', models.TextField(blank=True, help_text='Any error messages if this specific agent task failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
