# Generated by Django 5.2.2 on 2025-06-11 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='user',
            field=models.ForeignKey(help_text='The user who initiated the scan.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='job',
            field=models.ForeignKey(help_text='The parent ScanJob this result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scans.scanjob'),
        ),
    ]
